### ISSUE TITLE
Fixed width gutter

### ISSUE THREAD

**Issue by mmjaeger** [thingsym/flexbox-grid-mixins#1]
Hello
I was wondering how difficult it would be to have the mixins also support fixed gutters like 40px or 2rem for instance?

**Comment by thingsym** [comment]
It does not support now.
Only percentage support.

Because, it can not be calculated in units of absolute and relative in Sass.

In the future, we believe that to be able to use the CSS calc() Function.

**Comment by thingsym** [comment]
Units other than percentage in Version 0.1.2 or later can now be set.
It is still in the experimental stage.

Can be set in the 'width' property, see:
https://www.w3.org/TR/CSS21/visudet.html#the-width-property
