### ISSUE TITLE
Do not use shorthand syntax in maxin parameters

### ISSUE THREAD

**Issue by luksak** [thingsym/flexbox-grid-mixins#2]
I was evaluating flexbox grid mixins and encountered something I don't like: the $flex-flow parameter of the grid() mixin modifies a CSS shorthand property. I'd prefer having tow separate parameters: $flex-direction and $flex-wrap since this is cleaner an more flexible.

**Comment by thingsym** [comment]
Thank you for the improvement plan.
This was implemented in version 0.1.3.
have fun!
