### ISSUE TITLE
Shorthand flex property issue on IE11

### ISSUE THREAD

**Issue by dekisha** [thingsym/flexbox-grid-mixins#4]
Hi! I like your mixins very much and use them on a lot of projects.

However I noticed that IE11 has issues when using **flex** shorthand property.

Issue is described here https://stackoverflow.com/questions/32239549/flex-property-not-working-in-ie

I've usually fixed this by separating **flex** property into three: **flex-basic**, **flex-shrink** and **flex-grow**.

**Comment by thingsym** [comment]
Hi!
Thank you for report.

This was implemented in version 0.1.5.

Using the **$shorthand** Argument with grid-col().

It switch property. Use flex property as shorthand or three properties flex-basis, flex-grow and flex-shrink.

**Comment by dekisha** [comment]
Excellent solution! Thank you!

These mixins still rocks :1st_place_medal:
