### ISSUE TITLE
Option not to output box-sizing

### ISSUE THREAD

**Issue by maikeldaloo** [thingsym/flexbox-grid-mixins#5]
Hello, very nice work on the mixins.
Just a minor suggestion, most of us use the [inherited box-sizing](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) approach for our projects, so it's not necessary to output `box-sizing: border-box` with every mixin call. Maybe try doing something like this:

```
@charset 'utf-8';

$flexbox-grid-output-box-sizing: true !default;

@mixin grid($display: flex, $flex-direction: null, $flex-wrap: null, $flex-flow: null, $justify-content: null, $align-items: null, $align-content: null, $gutter: null, $grid-type: skeleton)
{
	@if $flexbox-grid-output-box-sizing {
		box-sizing: border-box;
	}

	@if $display {
		display: $display;
	}
...

@mixin grid-col($col: null, $grid-columns: 12, $col-offset: null, $gutter: null, $condensed: false, $align-self: null, $flex-grow: 0, $flex-shrink: 1, $flex-basis: auto, $order: null, $shorthand: true, $grid-type: skeleton, $last-child: false, $width: null, $max-width: null, $min-width: null, $height: null, $max-height: null, $min-height: null)
{
	@if $flexbox-grid-output-box-sizing {
		box-sizing: border-box;
	}

	@if type-of($col) == number and unitless($col) == true {
		$flex-shrink: 0;
		$flex-basis: percentage($col / $grid-columns);
...
```

This would keep your functionality exactly as it is, but provide an option for people not to output box-sizing for every call to your mixins.

For people who have used the inherited box-sizing approach, they can do:
```
$flexbox-grid-output-box-sizing: false;
@import 'node_modules/flexbox-grid-mixins/sass/flexbox-grid-mixins';
```

**Comment by thingsym** [comment]
Hi! @maikeldaloo
Thank you for suggestion.

This was implemented in version 0.1.6.

Add Variable Defaults **$flexbox-grid-mixins-box-sizing**.

* Variable Defaults is `$flexbox-grid-mixins-box-sizing: border-box`.
* `$flexbox-grid-mixins-box-sizing: border-box` or `$flexbox-grid-mixins-box-sizing: content-box` are explicit settings.
* `$flexbox-grid-mixins-box-sizing: null` don't output box-sizing property. Using initial box-sizing value as content-box or inherited box-sizing value.

example:
* https://thingsym.github.io/flexbox-grid-mixins/example/box-sizing.html
* https://github.com/thingsym/flexbox-grid-mixins/blob/master/docs/sass/box-sizing.scss
* https://github.com/thingsym/flexbox-grid-mixins/blob/master/docs/css/box-sizing.css

For people who have used the inherited box-sizing approach, they can do:

```
$flexbox-grid-mixins-box-sizing: null;
@import 'node_modules/flexbox-grid-mixins/sass/flexbox-grid-mixins';
```
